### ISSUE TITLE
"luarocks install sundown" doesn't work

### ISSUE THREAD

**Issue by yashoteja** [torch/rocks#38]
Hi,
Apologies in case this is not the right place for this question.
I am trying to install sundown using luarocks by using:

> /usr/local/bin/luarocks install sundown

while logged in as root.
This fails with following message:

> Installing https://raw.github.com/torch/rocks/master/sundown-scm-1.rockspec...
> Using https://raw.github.com/torch/rocks/master/sundown-scm-1.rockspec... switching to 'build' mode
> Cloning into 'sundown-ffi'...
> fatal: unable to connect to github.com:
> github.com[0: 192.30.252.130]: errno=Connection refused
> Error: Failed cloning git repository.

I suspect that this is because git:// port is blocked for me, and I use https:// port while git cloning. But I don't know how to force luarocks to use https:// port instead of git://

Because of this issue, the 2-line torch installation command from "http://torch.ch/" does not work for me, since it uses luarocks.
Can someone please tell me how to overcome this issue?

Thanks!

**Comment by sonamsingh19** [comment]
Same issue. I was using a server over ssh(torch on server). luarocks couldn't install anything due to same error.

Final solution which worked for me was to use this in terminal :
 git config --global url.https://github.com/.insteadOf git://github.com/

**Comment by aseempatni** [comment]
Thanks @sonamsingh19 `git config --global url.https://github.com/.insteadOf git://github.com/` solved the issue.

**Comment by PrincipalComponent** [comment]
Thanks **@sonamsingh19**. Had the same issue, your solution solved it.

**Comment by MInner** [comment]
@sonamsingh19 worked for me as well!

**Comment by christopher5106** [comment]
Thanks all!

**Comment by adam-erickson** [comment]
@sonamsingh19 solution worked for me on OSX 10.11.

**Comment by bityob** [comment]
Thanks @sonamsingh19.

**Comment by saurabhbajaj123** [comment]
thanks @sonamsingh19.

**Comment by saviogeorge** [comment]
@sonamsingh19 yes this did solve the issue

**Comment by realwenlongwang** [comment]
@sonamsingh19 Thanks!!

**Comment by yanelike** [comment]
Thanks!!

**Comment by springshuai** [comment]
Same issue here, @sonamsingh19's solution worked, thanks!

**Comment by sethrj** [comment]
Surprised this hasn't been fixed in three years. Is it that uncommon for a corporate firewall to block outgoing `git://` requests? Had to `export GIT_TRACE=1` during `spack install lmod` to find out that it wasn't installing because of this clone attempt. Thanks @sonamsingh19 for the solution!

**Comment by ineron** [comment]
@sonamsingh19 solution worked for me on Centos 7
Thanks!!

**Comment by eduamf** [comment]
@vervenumen solution worked for me on Ubuntu 16.
Thanks

**Comment by seclorum** [comment]
This is a viable workaround, but will luarocks ever be brought into the modern era?
