### ISSUE TITLE
how to install torch-rocks

### ISSUE THREAD

**Issue by YitzhakSp** [torch/rocks#82]
Trying to install the mnist dataset (https://github.com/andresy/mnist). I need to run

$ torch-rocks install [somescript]

I have already installed Torch on Linux. However I get the error that the command 'torch-rocks' could not be found. I tried to search for a file which contains the string 'torch-rocks' on the disc but the OS did not find such a file. My question is:
how do I install torch-rocks ?

**Comment by szagoruyko** [comment]
do luarocks instead of torch-rocks
```
luarocks install mnist
```

**Comment by YitzhakSp** [comment]
Thanks, it worked !
